[package]
name = "xrt-waves"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Kirchhoff diffraction integral"

[dependencies]
xrt-core = { workspace = true }
xrt-math = { workspace = true }
ndarray = { workspace = true }
num-complex = { workspace = true }
rayon = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
xrt-sources = { workspace = true }
xrt-oes = { workspace = true }
approx = { workspace = true }
criterion = { workspace = true }
serde_json = { workspace = true }

[[bench]]
name = "diffraction"
harness = false
