[package]
name = "xrt-waves"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Kirchhoff diffraction integral"

[dependencies]
xrt-core = { workspace = true }
xrt-math = { workspace = true }
ndarray = { workspace = true }
num-complex = { workspace = true }
rayon = { workspace = true }
thiserror = { workspace = true }
